version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: movies-db
    restart: always
    environment:
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: Z8HxwzkPdZ26
      POSTGRES_DB: moviesdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
